apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-persistent-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
